@startuml

actor "Project Manager" as PM
actor "Business Analyst" as BA
actor "Software Engineer" as SE
actor "Security Analyst" as sec

actor "Enterprise Compliance" as ent

actor "Target Environment" as target

rectangle TXML {
	usecase "Generate Application" as UC_ga
	usecase "Security Report" as UC_srs
	usecase "Generate Requirement" UC_req
}

SE --> UC_ga


@enduml